development:
  adapter: postgresql
  encoding: unicode
  database: nsstyleguide_development
  pool: 5
  username: 
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: nsstyleguide_test
  pool: 5
  username: 
  password:
  host: localhost
  port: 5432


